@echo off
cd /d "E:\OneDrive\CoWorkSpace\Tech Stack\Platform\plugin\mobility-trailblazers\.devcontainer"
echo Current directory: %CD%
echo Stopping and removing containers...
docker-compose down -v --remove-orphans
echo Cleaning up Docker system...
docker system prune -f
echo Building and starting services...
docker-compose up -d --build
echo Checking status...
docker-compose ps
pause
