version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: mobility_wordpress_dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Wp7kL9xP2qR7vN6wE3zY4uC1sA5f
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_TEMP_DIR', '/var/www/html/wp-content/uploads/tmp');
        define('UPLOADS', 'wp-content/uploads');
    volumes:
      # mount the plugin code into the WordPress plugins directory
      - ..:/workspace:cached
      - ..:/var/www/html/wp-content/plugins/mobility-trailblazers:cached
      # persist WordPress files (themes, uploads, etc)
      - wordpress_data:/var/www/html
      # temporary upload directory
      - tmp:/var/www/html/wp-content/uploads/tmp
    depends_on:
      - db
      - redis

  wpcli:
    image: wordpress:cli-php8.2
    container_name: mobility_wpcli_dev
    user: "33:33"
    depends_on:
      - db
      - wordpress
      - redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Wp7kL9xP2qR7vN6wE3zY4uC1sA5f
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_TEMP_DIR', '/var/www/html/wp-content/uploads/tmp');
        define('UPLOADS', 'wp-content/uploads');
    volumes:
      - ..:/workspace:cached
      - ..:/var/www/html/wp-content/plugins/mobility-trailblazers:cached
      - wordpress_data:/var/www/html
    command: tail -f /dev/null

  db:
    image: mariadb:11
    container_name: mobility_mariadb_dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: Rt9mK3nQ8xY7bV5cZ2wE4rT6yU1i
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: Wp7kL9xP2qR7vN6wE3zY4uC1sA5f
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: mobility_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mobility_phpmyadmin_dev
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Rt9mK3nQ8xY7bV5cZ2wE4rT6yU1i
      PMA_ARBITRARY: 1
      HIDE_PHP_VERSION: 1
    depends_on:
      - db

volumes:
  wordpress_data:
  db_data:
  redis_data:
  tmp: